<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            [
                'title' => 'Dashboard',
                'url' => 'dashboard',
                'icon' => 'ri-dashboard-2-line',
                'parent_id' => null,
                'order' => 1,
                'data_key' => 'dashboard',
                'status' => 1,
                'created_at' => '2024-11-13 11:52:12',
                'updated_at' => '2024-11-15 12:32:10',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Master',
                'url' => '#Master',
                'icon' => 'ri-apps-2-line',
                'parent_id' => null,
                'order' => 2,
                'data_key' => 'master',
                'status' => 1,
                'created_at' => '2024-11-13 11:53:42',
                'updated_at' => '2024-11-15 12:32:07',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Menu',
                'url' => 'menu',
                'icon' => null,
                'parent_id' => null, 
                'order' => 1,
                'data_key' => 'menu',
                'status' => 1,
                'created_at' => '2024-11-13 11:54:23',
                'updated_at' => '2024-11-16 22:38:37',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Permissions',
                'url' => 'permissions',
                'icon' => null,
                'parent_id' => null,
                'order' => 3,
                'data_key' => 'permissions',
                'status' => 1,
                'created_at' => '2024-11-14 10:47:34',
                'updated_at' => '2024-11-16 22:50:10',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Config',
                'url' => '#Setting',
                'icon' => 'ri-settings-5-line',
                'parent_id' => null,
                'order' => 4,
                'data_key' => 'config',
                'status' => 1,
                'created_at' => '2024-11-14 11:04:07',
                'updated_at' => '2024-12-21 10:49:05',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Roles',
                'url' => 'roles',
                'icon' => null,
                'parent_id' => null,
                'order' => 0,
                'data_key' => 'roles',
                'status' => 1,
                'created_at' => '2024-11-14 11:21:47',
                'updated_at' => '2024-11-15 12:32:01',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Users',
                'url' => 'users',
                'icon' => 'ri-file-user-line',
                'parent_id' => null,
                'order' => 3,
                'data_key' => 'users',
                'status' => 1,
                'created_at' => '2024-11-15 09:06:31',
                'updated_at' => '2024-11-15 12:31:58',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Settings',
                'url' => '#Settings',
                'icon' => 'ri-list-settings-fill',
                'parent_id' => null,
                'order' => 5,
                'data_key' => 'settings',
                'status' => 1,
                'created_at' => '2024-12-21 10:50:31',
                'updated_at' => '2024-12-21 10:50:31',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Financial Year Set',
                'url' => 'financial',
                'icon' => null,
                'parent_id' => null, 
                'order' => 1,
                'data_key' => 'financial-year-set',
                'status' => 1,
                'created_at' => '2024-12-21 10:51:26',
                'updated_at' => '2024-12-21 10:52:19',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Claim Master',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 2,
                'data_key' => 'claim-master',
                'status' => 1,
                'created_at' => '2024-12-21 10:52:44',
                'updated_at' => '2024-12-21 10:52:44',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Help Edit',
                'url' => 'helpedit',
                'icon' => null,
                'parent_id' => null,
                'order' => 3,
                'data_key' => 'help-edit',
                'status' => 1,
                'created_at' => '2024-12-21 10:53:04',
                'updated_at' => '2024-12-27 05:16:10',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Vehicle Slab Masters',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 4,
                'data_key' => 'vehicle-slab-masters',
                'status' => 1,
                'created_at' => '2024-12-21 10:53:28',
                'updated_at' => '2024-12-21 10:53:28',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Open Month',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 5,
                'data_key' => 'open-month',
                'status' => 1,
                'created_at' => '2024-12-21 10:54:12',
                'updated_at' => '2024-12-21 10:54:12',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Help Manual',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 6,
                'data_key' => 'help-manual',
                'status' => 1,
                'created_at' => '2024-12-21 10:54:36',
                'updated_at' => '2024-12-21 10:54:36',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Check Dup',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 6,
                'data_key' => 'check-dup',
                'status' => 1,
                'created_at' => '2024-12-21 10:55:05',
                'updated_at' => '2024-12-21 10:55:05',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Report',
                'url' => '#Report',
                'icon' => 'ri-file-chart-line',
                'parent_id' => null,
                'order' => 6,
                'data_key' => 'report',
                'status' => 1,
                'created_at' => '2024-12-21 10:56:17',
                'updated_at' => '2024-12-21 11:23:23',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Claim Report',
                'url' => '#',
                'icon' => null,
                'parent_id' => null, 
                'order' => 1,
                'data_key' => 'claim-report',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Daily Activity',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 1,
                'data_key' => 'daily-activity',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Claim Stage - I',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 2,
                'data_key' => 'claim-stage---i',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 11:24:50',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Claim Stage - II',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 3,
                'data_key' => 'claim-stage---ii',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 11:25:04',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Employee Status',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 4,
                'data_key' => 'employee-status',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Deactivate Claim',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 5,
                'data_key' => 'deactivate-claim',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Deactivate Claim (After Filled)',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 6,
                'data_key' => 'deactivate-claim-after-filled',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Claim Amount',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 7,
                'data_key' => 'claim-amount',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Top Rating (Same Day Upload)',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 8,
                'data_key' => 'top-rating-(same-day-upload)',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 11:03:46',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Deviation Reports (Xeasy->Focus)',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 9,
                'data_key' => 'deviation-reports-xeasy-focus',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Expense (Sunday & Holiday)',
                'url' => '#',
                'icon' => null,
                'parent_id' => null,
                'order' => 10,
                'data_key' => 'expense-sunday-holiday',
                'status' => 1,
                'created_at' => '2024-12-21 10:57:49',
                'updated_at' => '2024-12-21 10:57:49',
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'title' => 'Claim',
                'url' => '#',
                'icon' => 'ri-money-rupee-circle-line',
                'parent_id' => null,
                'order' => 2,
                'data_key' => 'claim',
                'status' => 1,
                'created_at' => '2024-12-21 11:07:28',
                'updated_at' => '2024-12-21 11:07:28',
                'created_by' => null,
                'updated_by' => null,
            ],
        ];

        DB::table('menus')->insert($menus);
    }
}