<?php
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\PermissionController;
use App\Http\Controllers\admin\PermissionGroupController;
use App\Http\Controllers\admin\RolesController;
use App\Http\Controllers\admin\MenuController;
use App\Http\Controllers\admin\UsersController;
use App\Http\Controllers\admin\SettingController;
use App\Http\Controllers\admin\ReportController;
use App\Http\Controllers\admin\FinancialYearController;
use App\Http\Controllers\admin\FilterController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\admin\ClaimViewController;
use App\Http\Controllers\admin\APIManagerController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
Route::get('', function () {
    return redirect()->route('login');
});
Route::get('clear-all-cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    Artisan::call('optimize:clear');
    return response()->json(['message' => 'All caches cleared successfully.']);
});
Auth::routes();
Route::middleware('auth')->group(function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::get('dashboard', [DashboardController::class, 'overview'])->name('dashboard');
    Route::post('admin/overview/filter', [DashboardController::class, 'filter'])->name('admin.overview.filter');
    Route::resource('permissions', PermissionController::class);
    Route::resource('permission-groups', PermissionGroupController::class);
    Route::post('permissions/assign', [PermissionController::class, 'assignPermissions'])->name('permissions.assign');
    Route::get('permissions-list', [PermissionController::class, 'getAllPermissions'])->name('permissions.all');
    Route::resource('roles', RolesController::class);
    Route::get('get-roles', [RolesController::class, 'getRoles'])->name('roles.getRoles');
    Route::resource('users', UsersController::class);
    Route::get('users/{id}/permissions', [PermissionController::class, 'getPermissions'])->name('users.permissions');
    Route::post('users/{id}/permissions/assign', [PermissionController::class, 'assignPermission'])->name('users.permissions.assign');
    Route::post('users/{id}/permissions/revoke', [PermissionController::class, 'revokePermission'])->name('users.permissions.revoke');
    Route::get('profile', [UsersController::class, 'profile'])->name('users.profile');
    Route::resource('menu', MenuController::class);
    Route::get('menu-list', [MenuController::class, 'menuList'])->name('menu.all');
    Route::get('menus/{menu}/logs', [MenuController::class, 'getLogs'])->name('menus.logs');
    Route::resource('financial', FinancialYearController::class);
    Route::get('settings', [SettingController::class, 'index'])->name('settings');
    Route::get('company', [SettingController::class, 'company'])->name('company');
    Route::get('get-company-config/{id}', [SettingController::class, 'getCompanyConfig'])->name('company.config.get');
    Route::post('save-config', [SettingController::class, 'saveCompanyConfig'])->name('company.config.save');
    Route::get('claim-report', [ReportController::class, 'claimReport'])->name('admin.claim_report');
    Route::get('daily-activity', [ReportController::class, 'dailyActivity'])->name('daily-activity');
    Route::get('functions', [ReportController::class, 'getFunction'])->name('report.functions');
    Route::get('verticals', [ReportController::class, 'getVertical'])->name('report.verticals');
    Route::get('departments', [ReportController::class, 'getDepartment'])->name('report.departments');
    Route::get('claim-types', [ReportController::class, 'getClaimTypes'])->name('report.claim_types');
    Route::post('filter-claims', [ReportController::class, 'filterClaims'])->name('report.filter_claims');
    Route::post('expense-claims/export', [ReportController::class, 'export'])->name('expense-claims.export');
    Route::post('daily-activity/data', [ReportController::class, 'getDailyActivityData'])->name('daily-activity.data');
    Route::post('daily-activity/export', [ReportController::class, 'exportDailyActivity'])->name('daily-activity.export');
    Route::post('employees/by-department', [FilterController::class, 'getEmployeesByDepartment']);
    Route::post('verticals/by-function', [FilterController::class, 'getVerticalsByFunction']);
    Route::post('departments/by-vertical', [FilterController::class, 'getDepartmentsByVertical']);
    Route::post('sub-departments/by-department', [FilterController::class, 'getSubDepartmentsByDepartment']);
    Route::post('employees/by-department', [FilterController::class, 'getEmployeesByDepartment']);
    Route::get('get-claim-detail-view', [ClaimViewController::class, 'getClaimDetailView']);
    Route::get('chat', [ChatController::class, 'index'])->name('chat');
    Route::get('chat/messages', [ChatController::class, 'fetchMessages']);
    Route::post('chat/send', [ChatController::class, 'sendMessage']);
    Route::get('chat/users', [ChatController::class, 'fetchUsers']);
    Route::post('chat/message/delete/{id}', [ChatController::class, 'delete'])->name('chat.message.delete');
    Route::resource('api-manager', APIManagerController::class)->names('api-manager');
    Route::get('fields-mapping/{claim_id}', [APIManagerController::class, 'showMappingPage'])->name('fields.mapping.page');
    Route::get('get-columns/{table}', [APIManagerController::class, 'getColumns'])->name('get.columns');
    Route::post('map-fields', [APIManagerController::class, 'mapFields'])->name('map.fields');
    Route::get('get-tables', [APIManagerController::class, 'getTables'])->name('get.tables');
    Route::post('fields-mapping/{claim_id}', [APIManagerController::class, 'storeFieldMapping'])->name('fields.mapping.store-fields-mapping');
    Route::get('fields/mapping/{claim_id}', [APIManagerController::class, 'getFieldMappings'])->name('fields.mapping.get');
    Route::post('settings/theme', [SettingController::class, 'saveThemeSettings'])->name('theme.save');
    Route::post('settings/general', [SettingController::class, 'saveGeneralSettings'])->name('settings.general.save');
    Route::get('settings/general', [SettingController::class, 'getGeneralSettings'])->name('settings.general.get');
});
